<?php
namespace frontend\components;

use yii\base\Widget;
use frontend\models\News;
use frontend\models\Post;
use frontend\models\Postcategory;

class AsideWidget extends Widget{

    public $view;
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $categories=null;
        if ($this->view=='blog'){
            $categories=Postcategory::find()->asArray()->all();
        }
        $postSidebar=Post::find()->orderBy('date DESC')->limit(3)->asArray()->all();
        $newsSidebar=News::find()->orderBy('date DESC')->limit(3)->asArray()->all();

       return $this->render('aside', ['newsSidebar'=>$newsSidebar, 'postSidebar'=>$postSidebar, 'categories'=>$categories]);
    }
}